version: 2
jobs:
  test:
    docker:
      - image: circleci/node:12
    steps:
      - add_ssh_keys:
          fingerprints:
            - "05:f0:05:8d:83:60:6f:f7:a9:84:65:97:a3:aa:53:4b"
      - checkout
      - run: yarn install --frozen-lockfile
      - run: yarn lint
      - run: yarn test
  do_release:
    docker:
      - image: circleci/node:12
    steps:
      - add_ssh_keys:
          fingerprints:
            - "05:f0:05:8d:83:60:6f:f7:a9:84:65:97:a3:aa:53:4b"
      - checkout
      - run:
          command: |
            COMMIT_MSG=$(git log --format=oneline -n 1 $CIRCLE_SHA1)
            if [[ $COMMIT_MSG == *"[skip-ci-version]"* ]]; then
              echo "[skip-ci-version] detected. Stopping."
              circleci step halt
            fi
      - run: yarn install --frozen-lockfile
      - run: yarn run build
      - run: git config --global user.email "$GIT_AUTHOR_EMAIL"
      - run: git config --global user.name "$GIT_AUTHOR_NAME"
      - run: yarn run release
  tag_latest:
    docker:
      - image: circleci/node:12
    steps:
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - checkout
      - run:
          name: Tag latest
          command: npm dist-tag add $(node -p "require('./package.json').name")@$(npm v . dist-tags.beta) latest
workflows:
  version: 2
  do_build:
    jobs:
      - test:
          context: public_package_publish
          filters:
            branches:
              ignore:
                - master
      - do_release:
          requires:
            - test
          context: public_package_publish
          filters:
            branches:
              only:
                - alpha
                - qa
                - dev
                - /prerelease-.*/
      - tag_latest:
          context: public_package_publish
          filters:
            branches:
              only:
                - master